INSERT INTO exams (code, name) VALUES
  ('WAEC','WAEC'), ('TOEFL','TOEFL'), ('SAT','SAT'), ('GRE','GRE')
ON CONFLICT (code) DO NOTHING;

-- WAEC: 3 departments (Science | Art | Commerce).
-- General subjects for all: English Language, Mathematics, Civic Education.
-- 5 distinct subjects per department.
INSERT INTO topics (id, exam_code, subject, name, department) VALUES
  (10,'WAEC','English Language','English Language','General'),
  (11,'WAEC','Mathematics','Mathematics','General'),
  (12,'WAEC','Civic Education','Civic Education','General'),
  (13,'WAEC','Physics','Physics','Science'),
  (14,'WAEC','Chemistry','Chemistry','Science'),
  (15,'WAEC','Biology','Biology','Science'),
  (16,'WAEC','Further Mathematics','Further Mathematics','Science'),
  (17,'WAEC','Geography','Geography','Science'),
  (18,'WAEC','Literature in English','Literature in English','Art'),
  (19,'WAEC','Government','Government','Art'),
  (20,'WAEC','History','History','Art'),
  (21,'WAEC','Christian Religious Studies','Christian Religious Studies','Art'),
  (22,'WAEC','Visual Arts','Visual Arts','Art'),
  (23,'WAEC','Economics','Economics','Commerce'),
  (24,'WAEC','Financial Accounting','Financial Accounting','Commerce'),
  (25,'WAEC','Commerce','Commerce','Commerce'),
  (26,'WAEC','Marketing','Marketing','Commerce'),
  (27,'WAEC','Business Management','Business Management','Commerce'),
  (4,'TOEFL','Reading','Inference',''),
  (5,'SAT','Math','Linear equations',''),
  (6,'GRE','Quant','Arithmetic','')
ON CONFLICT (id) DO NOTHING;
SELECT setval('topics_id_seq', 27);

INSERT INTO notes (topic_id, body_md) VALUES
  (10,'# English Language\n\n- Concord: singular subjects take singular verbs.\n- "It''s" = it is; "its" = belonging to it.\n- Read passages twice before answering.'),
  (11,'# Mathematics\n\n- Linear: isolate x. Quadratic: (x-a)(x-b)=0.\n- Pythagoras: a^2+b^2=c^2. Triangle angles sum to 180°.'),
  (12,'# Civic Education\n\n- Rights come with duties: vote, obey laws, pay taxes.\n- Democracy: government by the people through elections.'),
  (13,'# Physics\n\n- v = u + at. F = ma. Units matter: N, J, W.'),
  (14,'# Chemistry\n\n- H2O, CO2, NaCl: know common formulae.\n- Acids turn blue litmus red.'),
  (15,'# Biology\n\n- Photosynthesis: CO2 + water → glucose + O2.\n- Cell powerhouse: mitochondria.'),
  (16,'# Further Mathematics\n\n- f(x)=2x-1 → f(4)=7.\n- Roots of x^2-5x+6: 2 and 3.'),
  (17,'# Geography\n\n- Lines of latitude run parallel to the equator.\n- Harmattan: dry dusty wind from the Sahara.'),
  (18,'# Literature in English\n\n- Prose, poetry, drama: know the genres.\n- A simile uses "like" or "as".'),
  (19,'# Government\n\n- Three arms: executive, legislature, judiciary.\n- ECOWAS HQ is in Abuja.'),
  (20,'# History\n\n- Nigeria gained independence in 1960.\n- First president: Nnamdi Azikiwe.'),
  (21,'# Christian Religious Studies\n\n- The Sermon on the Mount: Matthew 5–7.\n- Joseph was sold by his brothers.'),
  (22,'# Visual Arts\n\n- Primary colours: red, blue, yellow.\n- Green = blue + yellow.'),
  (23,'# Economics\n\n- Scarcity forces choice; scale of preference orders wants.\n- Demand falls as price rises.'),
  (24,'# Financial Accounting\n\n- Assets = Capital + Liabilities.\n- Debit the receiver, credit the giver.'),
  (25,'# Commerce\n\n- Trade = buying and selling; aids to trade include banking, insurance, transport.\n- Retailer sells to final consumers.'),
  (26,'# Marketing\n\n- 4Ps: product, price, place, promotion.\n- Market segmentation groups similar buyers.'),
  (27,'# Business Management\n\n- Planning, organising, leading, controlling.\n- An entrepreneur bears business risks.')
ON CONFLICT (topic_id) DO NOTHING;

INSERT INTO questions (exam_code, topic_id, stem, options, answer_idx, explanation, difficulty) VALUES
('WAEC',11,'If 2x + 3 = 11, x = ?','["2","3","4","5"]',2,'2x = 8, so x = 4.',1),
('WAEC',11,'Roots of x^2 - 5x + 6 = 0?','["1,6","2,3","-2,-3","0,5"]',1,'(x-2)(x-3)=0.',2),
('WAEC',11,'Hypotenuse of a 3-4 right triangle?','["5","6","7","12"]',0,'3^2+4^2=25, sqrt=5.',1),
('WAEC',11,'Sum of interior angles of a triangle?','["90°","180°","270°","360°"]',1,'Always 180°.',1),
('WAEC',10,'Choose the correctly punctuated sentence.','["Its raining.","It''s raining.","Its'' raining.","It raining."]',1,'"It''s" = it is.',2),
('WAEC',11,'If f(x)=2x-1, f(4)=?','["6","7","8","9"]',1,'2*4-1=7.',1),
('WAEC',11,'Simplify: 3(x - 2) + 4 = ?','["3x-2","3x-10","3x+2","3x-6"]',0,'3x-6+4 = 3x-2.',1),
('WAEC',11,'If y = 5x and x = 3, y = ?','["8","12","15","53"]',2,'5*3=15.',1),
('WAEC',11,'A rectangle is 8cm by 5cm. Area?','["13cm²","26cm²","40cm²","45cm²"]',2,'8*5=40.',1),
('WAEC',11,'Each angle of an equilateral triangle?','["45°","60°","90°","120°"]',1,'180/3=60.',1),
('WAEC',10,'Choose the correct option: She ___ to school daily.','["go","goes","going","gone"]',1,'Third-person singular takes "goes".',1),
('WAEC',10,'Which word is a noun?','["quickly","beautiful","honesty","run"]',2,'Honesty names a thing.',1),
('WAEC',11,'Solve: x/4 = 5. x = ?','["9","16","20","24"]',2,'x = 5*4 = 20.',2),
('WAEC',11,'Diameter of a circle with radius 7cm?','["7cm","10.5cm","14cm","21cm"]',2,'d = 2r = 14.',2),
('WAEC',12,'Which is a civic duty?','["Voting in elections","Cheating in exams","Littering streets","Dodging taxes"]',0,'Voting is a duty of citizens.',1),
('WAEC',12,'Democracy means government ___ the people.','["against","without","by","above"]',2,'Government by the people.',1),
('WAEC',13,'A car accelerates from 0 to 20 m/s in 5s. a = ?','["2 m/s²","4 m/s²","5 m/s²","100 m/s²"]',1,'a = 20/5 = 4.',2),
('WAEC',13,'SI unit of force?','["Joule","Watt","Newton","Pascal"]',2,'Force is measured in newtons.',1),
('WAEC',14,'Chemical formula of water?','["CO2","H2O","O2","NaCl"]',1,'Two hydrogen, one oxygen.',1),
('WAEC',14,'Blue litmus turns ___ in acid.','["blue","red","green","yellow"]',1,'Acids turn blue litmus red.',1),
('WAEC',15,'Site of photosynthesis?','["Mitochondria","Chloroplast","Nucleus","Ribosome"]',1,'Chlorophyll traps sunlight.',1),
('WAEC',15,'Powerhouse of the cell?','["Nucleus","Ribosome","Mitochondria","Vacuole"]',2,'Mitochondria release energy.',1),
('WAEC',16,'If g(x)=x^2, g(5)=?','["10","20","25","30"]',2,'5^2=25.',1),
('WAEC',16,'Gradient of y = 3x + 2?','["2","3","5","6"]',1,'Gradient is the x coefficient.',2),
('WAEC',17,'Lines parallel to the equator?','["Longitudes","Latitudes","Meridians","Contours"]',1,'Latitudes run parallel.',1),
('WAEC',17,'Harmattan blows from the ___?','["Atlantic","Sahara","Niger Delta","Gulf of Guinea"]',1,'Dry dusty Saharan wind.',1),
('WAEC',18,'"He fights like a lion" is a ___?','["metaphor","simile","hyperbole","irony"]',1,'Uses "like".',1),
('WAEC',18,'A play is written to be ___?','["read silently","performed","sung","painted"]',1,'Drama is for performance.',1),
('WAEC',19,'How many arms of government?','["Two","Three","Four","Five"]',1,'Executive, legislature, judiciary.',1),
('WAEC',19,'ECOWAS headquarters is in ___?','["Accra","Lagos","Abuja","Dakar"]',2,'Abuja, Nigeria.',1),
('WAEC',20,'Nigeria gained independence in ___?','["1957","1960","1963","1966"]',1,'1 October 1960.',1),
('WAEC',20,'Nigeria''s first president?','["Tafawa Balewa","Obafemi Awolowo","Nnamdi Azikiwe","Ahmadu Bello"]',2,'Azikiwe, 1963.',2),
('WAEC',21,'The Sermon on the Mount is in ___?','["Mark 1","Matthew 5–7","Luke 10","John 3"]',1,'Matthew chapters 5 to 7.',2),
('WAEC',21,'Who was sold by his brothers?','["Moses","David","Joseph","Samuel"]',2,'Joseph, Genesis 37.',1),
('WAEC',22,'Primary colours are ___?','["Red, green, blue","Red, blue, yellow","Black, white, grey","Orange, purple, green"]',1,'Red, blue, yellow.',1),
('WAEC',22,'Blue + yellow gives ___?','["Orange","Purple","Green","Brown"]',2,'Mixing primaries.',1),
('WAEC',23,'Scale of preference helps to ___?','["Print money","Arrange wants","Raise prices","Avoid scarcity"]',1,'Orders wants by importance.',1),
('WAEC',23,'When price rises, quantity demanded ___?','["rises","falls","stays","doubles"]',1,'First law of demand.',1),
('WAEC',24,'Assets = Capital + ___?','["Drawings","Liabilities","Sales","Discounts"]',1,'Accounting equation.',2),
('WAEC',24,'Debit the ___, credit the giver.','["owner","receiver","debtor","bank"]',1,'Double-entry rule.',1),
('WAEC',25,'A retailer sells to ___?','["wholesalers","producers","final consumers","importers"]',2,'End of distribution chain.',1),
('WAEC',25,'Which is an aid to trade?','["Farming","Banking","Sleeping","Cooking"]',1,'Banking supports trade.',1),
('WAEC',26,'The 4Ps exclude ___?','["product","price","people","promotion"]',2,'Product, price, place, promotion.',2),
('WAEC',26,'Segmentation groups buyers by ___?','["height","similar traits","surnames","luck"]',1,'Similar needs group together.',1),
('WAEC',27,'An entrepreneur is known for ___?','["Avoiding risk","Bearing risk","Avoiding profit","Avoiding plans"]',1,'Risk-bearing is central.',1),
('WAEC',27,'Which is a management function?','["Eating","Planning","Sleeping","Dancing"]',1,'Plan, organise, lead, control.',1),
('TOEFL',4,'"It rained, so the match was cancelled." The inference is:','["Rain causes cancellation","Matches never cancel","Rain is unlikely","Cancellation causes rain"]',0,'Effect follows cause.',2),
('SAT',5,'If 3x - 7 = 11, x = ?','["5","6","7","8"]',1,'3x=18, x=6.',1),
('GRE',6,'Which is greatest: 2^10, 10^2, 100*10?','["2^10","10^2","100*10","all equal"]',0,'2^10=1024 > 1000 > 100.',2),
('TOEFL',4,'"The library closes at 6pm." You arrive at 6:30. Inference?','["It is open","It is closed","It opens soon","It never closes"]',1,'After closing time.',1),
('TOEFL',4,'"She studied hard; therefore she passed." Therefore means?','["however","as a result","although","instead"]',1,'Conclusion marker.',1),
('TOEFL',4,'Passage says dolphins sleep with one eye open. We infer they ___?','["never sleep","stay alert","are blind","hunt at night"]',1,'One eye open = alert.',2),
('TOEFL',4,'"Despite the rain, the game continued." Despite shows ___?','["cause","contrast","time","place"]',1,'Contrast marker.',1),
('TOEFL',4,'Speaker: "I''m starving." Closest meaning?','["I am full","I am very hungry","I am tired","I am sick"]',1,'Starving = very hungry.',1),
('TOEFL',4,'"The results were ambiguous." Ambiguous means?','["clear","unclear","excellent","final"]',1,'Open to interpretation.',2),
('TOEFL',4,'Lecture mentions bees dance to show food location. Dance is a form of ___?','["sleep","communication","attack","migration"]',1,'Sharing information.',2),
('TOEFL',4,'"He barely passed." Barely means?','["easily","almost not","certainly","quickly"]',1,'Only just.',1),
('TOEFL',4,'Author lists three causes of erosion. The structure is ___?','["story","enumeration","dialogue","poem"]',1,'Listing = enumeration.',2),
('SAT',5,'If 2(x - 3) = 10, x = ?','["7","8","9","10"]',1,'2x-6=10, x=8.',1),
('SAT',5,'Slope of line through (1,2) and (3,8)?','["2","3","4","6"]',1,'(8-2)/(3-1)=3.',2),
('SAT',5,'If x² = 49 and x > 0, x = ?','["-7","7","14","98"]',1,'Positive root.',1),
('SAT',5,'30% of 200 = ?','["30","45","60","90"]',2,'0.3*200=60.',1),
('SAT',5,'If y = 3x + 5 and x = -2, y = ?','["-11","-1","1","11"]',1,'-6+5=-1.',2),
('SAT',5,'Median of 3, 7, 9, 12, 15?','["7","9","10","12"]',1,'Middle value.',1),
('SAT',5,'If a² - b² = 24 and a - b = 4, a + b = ?','["4","6","8","20"]',1,'(a-b)(a+b)=24.',2),
('SAT',5,'A car travels 120 miles in 2 hours. Speed?','["40 mph","50 mph","60 mph","120 mph"]',2,'120/2=60.',1),
('SAT',5,'If 5x + 2 = 3x + 10, x = ?','["2","4","6","8"]',1,'2x=8.',1),
('GRE',6,'If n is even, n² is ___?','["odd","even","prime","zero"]',1,'Even squared stays even.',1),
('GRE',6,'20% of 150 plus 10 = ?','["30","35","40","45"]',1,'30+10=40.',1),
('GRE',6,'If x + y = 10 and x - y = 4, x = ?','["3","5","7","9"]',2,'Add: 2x=14.',2),
('GRE',6,'√144 + √25 = ?','["12","17","19","29"]',1,'12+5=17.',1),
('GRE',6,'A quantity doubles every hour. After 3 hours, factor?','["3","6","8","9"]',2,'2³=8.',2),
('GRE',6,'If 3^k = 81, k = ?','["3","4","5","27"]',1,'3⁴=81.',1),
('GRE',6,'Average of 12, 18, 30?','["18","20","22","30"]',1,'60/3=20.',1),
('GRE',6,'If |x| = 7, x could be ___?','["only 7","only -7","7 or -7","0"]',2,'Absolute value.',1),
('GRE',6,'Slope of y = -2x + 9?','["9","2","-2","-9"]',2,'Coefficient of x.',2);
